#!/bin/sh

if [ ! "$UID" = 0 ]; then
        echo "This script must be run as root"
        exit 1
fi

chown proxy:proxy -R /var/lib/squidguard/db/*

find /var/lib/squidguard/db -type f | xargs chmod 640
find /var/lib/squidguard/db -type d | xargs chmod 750

echo -n "Updating squidGuard DBs..."
sudo -u proxy squidGuard -C all
echo " done!"

echo -n "Reloading Squid..."
squid3 -k reconfigure
echo " done!"
